### ISSUE TITLE
Support Craft 3.5

### ISSUE THREAD

**Issue by goraxan** [thejoshsmith/craft-fab-permissions#22]
Due to the new field layout redesign in Craft 3.5, the plugin fails to load with the following error
![image](https://user-images.githubusercontent.com/8337784/89996017-90228380-dc8a-11ea-8c69-6dac45d1b341.png)

**Comment by thejoshsmith** [comment]
Thanks Pere, I’ll aim to put aside some time over the next week or two to
upgrade the plugin for 3.5.

**Comment by adrianbunea** [comment]
Hello, I've also stumbled upon this issue. How is the upgrade for 3.5 going?

**Comment by JoshCoady** [comment]
FYI #23 adds support for existing data but not the control panel UI

**Comment by thejoshsmith** [comment]
Thanks @JoshCoady, that's great! Really sorry about the delay here everyone.

**Comment by thejoshsmith** [comment]
Update: halfway through updating the UI. Craft have changed quite a few things in 3.5 so in the process of figuring out a migration path.

**Comment by thejoshsmith** [comment]
Version 2.0.0 has been released with support for Craft 3.5.x 😅. I took the opportunity to upgrade the UI a bit and now a padlock appears on each tab/field instead of the red dot (docs will be updated soon). The padlock is clickable and will open the permissions modal as well as using the old link/button from the settings menu.

It should be possible to control permissions on the new UI elements so I'll add that to my to do list.

Let me know if there's any issues!

<img width="1407" alt="Screen Shot 2020-10-10 at 11 39 15 PM" src="https://user-images.githubusercontent.com/5515179/95653090-5d91eb80-0b52-11eb-83fc-2de5a8656915.png">
